### PR TITLE
Fix CVE dependency issue

### PR DESCRIPTION
**Pull request by CVEDetect**
Fix issue #105   by update dependency org.yaml:snakeyaml:1.33 @jreijn

### CODE REVIEW

**Comment by Vest** [comment]
@CVEDetect is it a virus?

**Comment by CVEDetect** [comment]
> @CVEDetect is it a virus?



> @CVEDetect is it a virus?

It is a cve vulnerability, there is a description of this vulnerability in #105

**Comment by Vest** [comment]
I saw it. Instead of blindly approving your PR, have you seen a direct dependency to snakeyaml in this repository?

If not, have you contacted the owners of dependencies that we use directly? If the vulnerability is fixed, I will bump Spring and other dependencies.

The last thing, have you tried to use this vulnerability in the current project? What was the outcome?

Thanks

**Comment by CVEDetect** [comment]
> I saw it. Instead of blindly approving your PR, have you seen a direct dependency to snakeyaml in this repository?
> 
> If not, have you contacted the owners of dependencies that we use directly? If the vulnerability is fixed, I will bump Spring and other dependencies.
> 
> The last thing, have you tried to use this vulnerability in the current project? What was the outcome?
> 
> Thanks

The version starting from spring 3.0.0 has upgraded the version of snakeyaml to 1.33 to fix this vulnerability

**Comment by Vest** [comment]
I am glad, you came to the same conclusion. And I hope you understand, why I declined your PR. 
I working on the migration to Spring 3.

**Comment by CVEDetect** [comment]
thank you for your reply

**Comment by caoliang1918** [comment]
艹 艹 艹

**Pull request closed without merging**
