### PR TITLE
Add Ickenham to benchmark

### PR DESCRIPTION
**Pull request by enpassant**

### CODE REVIEW

**Comment by enpassant** [comment]
This resolves the #30

**Comment by Vest** [comment]
Hello @enpassant 

Would you be able to update your PR? I have changed the project structure significantly, and your PR is not valid anymore.

Thanks,
Vest

**Comment by enpassant** [comment]
Hello @Vest,

I have updated my PR. If you merge this then run the benchmark for this too, please.

Thanks!
Enpassant

**Comment by Vest** [comment]
Hello @enpassant,

Thank you for the PR. I have used it in the PR #46, but I had to do some minor changes.
I had to disable the caching in your ViewResolver, because we don't test the speed of cache, but the performance of template engines.

Kind regards,
Vest

**Pull request closed without merging**
