### PR TITLE
Updated frameworks

### PR DESCRIPTION
**Pull request by Vest**
Here is the list of frameworks that I have updated and tested.
- tomcat - 7.0.72;
- spring - 4.3.2;
- jquery - 3.1.1;
- freemarker - 2.3.25-incubating (the version should be updated after Apache accepts it);
- thymeleaf - 3.0.2;
- mustache - 1.3;
- scalate - 2.11;
- handlebars - 4.0.6;
- jade4j - 1.2.3.

### CODE REVIEW

**Comment by Vest** [comment]
There are frameworks  that are not updated, such as **velocity, httl, jtwig**. I do not know whether we need them or not. Some of them are very old.

Regarding freemarker - its version the "incubating" suffix. It will probably disappear when Apache accepts this version. When this happens, I can update the repository. Please tell me to do this.

jade4j is quite old, because the recent version is 1.2.5 (I think), but the spring extension is still old. You should see my comment in the issue #21.

**Comment by Vest** [comment]
Please update your measurements, if possible.
I will probably create the batch file that should receive the performance metrics and prepare some beautiful output :)

**Comment by jreijn** [comment]
WOW! Thanks for this incredible work. I will review this pull request in the morning, so we can merge it. I have some ideas on how we can automatically test for results, so I will create a new issue for it.

**Comment by Vest** [comment]
@jreijn, I have forgot to update URLs to jQuery (my fault). Now it should look fine - new bootstrap and jQuery.

**Pull request merged**
